# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-29 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import main_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20170825_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice',
            field=models.CharField(max_length=500, validators=[main_app.validators.validate_choice]),
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='main_app.Question'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main_app.Question'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='main_app.Comment'),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='main_app.Sport'),
        ),
    ]
